Traceback (most recent call last):
  File "/home1/npiccolotto/ensemble-sets/code/render2.py", line 543, in vis
    G = ctx.run(render)
  File "/home1/npiccolotto/ensemble-sets/code/render2.py", line 309, in render
    L = route(instance, G, element_set_partition)
  File "/home1/npiccolotto/ensemble-sets/code/util/route.py", line 1360, in route
    route_brosi_ilp(
  File "/home1/npiccolotto/ensemble-sets/code/util/route.py", line 740, in route_brosi_ilp
    model.addConstr(x[(u, v)] >= x_ew[(e, (u, v))])
  File "src/gurobipy/model.pxi", line 3629, in gurobipy.Model.addConstr
  File "src/gurobipy/model.pxi", line 3364, in gurobipy.Model.__addConstr
  File "src/gurobipy/constr.pxi", line 27, in gurobipy.Constr.__init__
  File "src/gurobipy/constr.pxi", line 71, in gurobipy.Constr.__setattr__
MemoryError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home1/npiccolotto/ensemble-sets/code/render2.py", line 568, in vis
    with open(
MemoryError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home1/npiccolotto/.pyenv/versions/3.10.13/lib/python3.10/site-packages/click/core.py", line 102, in augment_usage_errors
    yield
MemoryError

During handling of the above exception, another exception occurred:

MemoryError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home1/npiccolotto/ensemble-sets/code/render2.py", line 585, in <module>
    vis()
  File "/home1/npiccolotto/.pyenv/versions/3.10.13/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home1/npiccolotto/.pyenv/versions/3.10.13/lib/python3.10/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home1/npiccolotto/.pyenv/versions/3.10.13/lib/python3.10/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
MemoryError
