Traceback (most recent call last):
  File "/home1/npiccolotto/ensemble-sets/code/render2.py", line 578, in <module>
    vis()
  File "/home1/npiccolotto/.pyenv/versions/3.10.13/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home1/npiccolotto/.pyenv/versions/3.10.13/lib/python3.10/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home1/npiccolotto/.pyenv/versions/3.10.13/lib/python3.10/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home1/npiccolotto/.pyenv/versions/3.10.13/lib/python3.10/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home1/npiccolotto/ensemble-sets/code/render2.py", line 574, in vis
    raise e
  File "/home1/npiccolotto/ensemble-sets/code/render2.py", line 546, in vis
    metrics = calc_metrics(G, inst)
  File "/home1/npiccolotto/ensemble-sets/code/util/metrics.py", line 525, in compute_metrics
    "total_line_crossings": compute_crossings_inside(G_, what="lines")
  File "/home1/npiccolotto/ensemble-sets/code/util/metrics.py", line 446, in compute_crossings_inside
    _, a = list(
IndexError: list index out of range
